targetType: ENC[AES256_GCM,data:EBcw,iv:15E2bA+UjadooqJ5IZKR8NfU4RSgH4Z82CAmyd5BPOA=,tag:iKpdEQyq1myM5H5/8qcdqA==,type:str]
type: ENC[AES256_GCM,data:Ixo2bmAJ9dxQ,iv:tSpGTtUfl30Vc1UducwZ9RCluMqgftBE11HKz73qWvE=,tag:m9XEsvq1fxB3efJWY5Rq7A==,type:str]
name: ENC[AES256_GCM,data:lCy3q0v+N8tV6Z6Hgg==,iv:1wu8YbEWo/aWWYNDe71IR253+FaeUoW/hkAhXXh0vRQ=,tag:VrVVSpt6laysulM62MdMJQ==,type:str]
namespace: ENC[AES256_GCM,data:zu7mVhFv0Q==,iv:jALmIjBkgsD44TRKfkXd2H9w4D8xh+McU9hTIaCA7lQ=,tag:x4OX4rvgen4o0+dt824ZJA==,type:str]
data:
    someConfigMapKey: ENC[AES256_GCM,data:4/on1IGhmzgCQ2ys2N4=,iv:48q13Tlb+kAMAaGGCV21Wx8i0SsmhX8VXa1Acfx+LkE=,tag:yEKAarlvtHgDqnS5oN+L2w==,type:str]
    loremIpsum: ENC[AES256_GCM,data:fqLITszozNC2/Pt4vYPfPYYEXrn/O6KR5e45Awban2MEphmKOgurUGohINQwnGrNpAogetKiZFeqxCeBekPkt8uvkIbjfQxPOicQpt5MzEn3YqrkZVU3WzZPhFTpjHKdbdCZ7/hRq191A0PSJ2NA9RklGpRyDe6hnHyNTFQs1RdMo6iCPnP/uyyhvweHx853HJeO82LrpANOy6bmqugfnpnp5VGR+93913wd/l5vtWWhlwvuzynkz6lJzWSpZ1lRsCLgd/Y4zpc8cftQwNgAY9uBEEeOkiSlIcK7ffFw0NC4s0vIXwT+a3iaU0KL8FPVBH55hiqbbcYBYJikGuwtivgpKSTyzxIfdFj0RPsYhAZxeZXfSQhZ5wehGJJ/7xdJvBfzhGg61iApmvHmeApPzDHznZrgz6+h8ITwdIPrSQhth1v3ToWBn1L9QaBgIOnrac0mkEyjITfcFB+8Y8VNhjrDWlXOQIZTWCRWlIV5fD19qYiebMpqT6bpEWFT9rAAvi88hdshq8tuXFl1y/EWKdKoslFUT3jtaFQ7Hpxm42z9ucTk5HLIrSBUJB9HX9jd3WaKxFFl2YZBxXPsKSwRyuoMwDl08zuw759zDaTjXy32CMBNY21lfjMiMrEuAGiPqrhV1EIpZrs8oL+BinbYTeTjPzvxSoqWnKSn1pu5rOKHZInio2PhaWrYJ/0/SQI9r1k7gd+gcBpf5a3URwOgYJ4bmLizs3ujA34H2mV9vxjutr25kBoZvRz+sVl1S6wDTZRZbDnhGhDVL3eItpA=,iv:AsesjG191m981KVGyIaFYRYo3CpO7UJdBFwVxkl6Ik0=,tag:7xe4ON/zQuhJwxwc2XLkSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dc7m8a9mwkfl4hwy4p5drhamj2a9992hz2w76erqu59r8evsxa8qqdsna3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhd0RMc3V5endrNVpjcHo1
            Z1BBanRtNWtDVy9ZNUlHbEhtTTFIeElmYVI0CjY2Zm9VUmxleFJwSXZHaWJUek5V
            WnNsZWlYMVZzZUlSTitkNFVIZExpbFUKLS0tIGxVeWh4WFZNSkY0ZGZWOGR3bnVv
            cEs5TzdxVEM3TGoySE4yVnUvR1FqaGsKK4PFub3b84AKbcxKB5Wf/SPQPFiSJec3
            CbpGb0A9lmok0a4owoCIAhRA+UaUplpTp4IkL40xVgPYwvvnXfl4Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T13:13:18Z"
    mac: ENC[AES256_GCM,data:1Pda0G7boRt4zRgsw33Vzc+ef42G+DJfmde+wTT3ITiAI+OzJj+Xo+8JZqu6kJ7WcvLC1z+xwpDq90uedua8x8bE/+jyXEw2rFJgCL9C1j+gPCwxfYz4GQrF58t2jEm3dFPUbdIUWzk2ArV13I55xjiDxzHBeGqvzQ//wD43Pi0=,iv:dV9xCsPsHVaoCRjmoYEEkJUTB97bKEPa0rces4xcoug=,tag:5SjEJ5HbMuhWJGPLi3kXFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
