target: ENC[AES256_GCM,data:TnzF,iv:8RvsNPJdWMWDcmYiUGqeIjv1i4xzx81kMrxoUZdPQN0=,tag:iwsUoJDBPdvYFR2jTrgM1g==,type:str]
type: ENC[AES256_GCM,data:Ixo2bmAJ9dxQ,iv:tSpGTtUfl30Vc1UducwZ9RCluMqgftBE11HKz73qWvE=,tag:m9XEsvq1fxB3efJWY5Rq7A==,type:str]
name: ENC[AES256_GCM,data:lCy3q0v+N8tV6Z6Hgg==,iv:1wu8YbEWo/aWWYNDe71IR253+FaeUoW/hkAhXXh0vRQ=,tag:VrVVSpt6laysulM62MdMJQ==,type:str]
namespace: ENC[AES256_GCM,data:zu7mVhFv0Q==,iv:jALmIjBkgsD44TRKfkXd2H9w4D8xh+McU9hTIaCA7lQ=,tag:x4OX4rvgen4o0+dt824ZJA==,type:str]
data:
    someConfigMapKey: ENC[AES256_GCM,data:4/on1IGhmzgCQ2ys2N4=,iv:48q13Tlb+kAMAaGGCV21Wx8i0SsmhX8VXa1Acfx+LkE=,tag:yEKAarlvtHgDqnS5oN+L2w==,type:str]
    loremIpsum: ENC[AES256_GCM,data:fqLITszozNC2/Pt4vYPfPYYEXrn/O6KR5e45Awban2MEphmKOgurUGohINQwnGrNpAogetKiZFeqxCeBekPkt8uvkIbjfQxPOicQpt5MzEn3YqrkZVU3WzZPhFTpjHKdbdCZ7/hRq191A0PSJ2NA9RklGpRyDe6hnHyNTFQs1RdMo6iCPnP/uyyhvweHx853HJeO82LrpANOy6bmqugfnpnp5VGR+93913wd/l5vtWWhlwvuzynkz6lJzWSpZ1lRsCLgd/Y4zpc8cftQwNgAY9uBEEeOkiSlIcK7ffFw0NC4s0vIXwT+a3iaU0KL8FPVBH55hiqbbcYBYJikGuwtivgpKSTyzxIfdFj0RPsYhAZxeZXfSQhZ5wehGJJ/7xdJvBfzhGg61iApmvHmeApPzDHznZrgz6+h8ITwdIPrSQhth1v3ToWBn1L9QaBgIOnrac0mkEyjITfcFB+8Y8VNhjrDWlXOQIZTWCRWlIV5fD19qYiebMpqT6bpEWFT9rAAvi88hdshq8tuXFl1y/EWKdKoslFUT3jtaFQ7Hpxm42z9ucTk5HLIrSBUJB9HX9jd3WaKxFFl2YZBxXPsKSwRyuoMwDl08zuw759zDaTjXy32CMBNY21lfjMiMrEuAGiPqrhV1EIpZrs8oL+BinbYTeTjPzvxSoqWnKSn1pu5rOKHZInio2PhaWrYJ/0/SQI9r1k7gd+gcBpf5a3URwOgYJ4bmLizs3ujA34H2mV9vxjutr25kBoZvRz+sVl1S6wDTZRZbDnhGhDVL3eItpA=,iv:AsesjG191m981KVGyIaFYRYo3CpO7UJdBFwVxkl6Ik0=,tag:7xe4ON/zQuhJwxwc2XLkSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dc7m8a9mwkfl4hwy4p5drhamj2a9992hz2w76erqu59r8evsxa8qqdsna3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhd0RMc3V5endrNVpjcHo1
            Z1BBanRtNWtDVy9ZNUlHbEhtTTFIeElmYVI0CjY2Zm9VUmxleFJwSXZHaWJUek5V
            WnNsZWlYMVZzZUlSTitkNFVIZExpbFUKLS0tIGxVeWh4WFZNSkY0ZGZWOGR3bnVv
            cEs5TzdxVEM3TGoySE4yVnUvR1FqaGsKK4PFub3b84AKbcxKB5Wf/SPQPFiSJec3
            CbpGb0A9lmok0a4owoCIAhRA+UaUplpTp4IkL40xVgPYwvvnXfl4Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-05T11:28:22Z"
    mac: ENC[AES256_GCM,data:I3w0upkHYHYOSZP/cV1uKnNAjb3uHrE+EzCQ/YHw95Rk59T+chg1UN2n/nCpRwUZ85a0bAYDpIpI9IA3r0g7uu//+8Li0jv38oofCN4g0bkMJtHEbSGcLvbjzzK+hNdz8Qr8BjiWN4uvi9cXv3bFczh0gkRh4f3AGotB392C3G4=,iv:Se7j3Pj11DT9/qJ2USdkCrAUPHi9YEN9/z3VSNV/sbQ=,tag:uEP4vxDcGWi6Qne+Bw6mqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
