name: Build

on:
  push:
    tags:
      - 2.*

jobs:
  test:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        os: [ubuntu-latest, ubuntu-18.04, windows-latest, macos-11]
        include:
          - os: ubuntu-latest
            os_name: ubuntu
            artifact_suffix: ""
          - os: ubuntu-18.04
            os_name: ubuntu-18.04
            artifact_suffix: ""
          - os: windows-latest
            os_name: windows
            artifact_suffix: ".exe"
          - os: macos-11
            os_name: macos
            artifact_suffix: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: golang build
        run: |
          cd cmd/gitops
          GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" .
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/cmd/gitops/gitops${{ matrix.artifact_suffix }}
          asset_name: gitops_${{ matrix.os_name }}_${{ matrix.arch }}${{ matrix.artifact_suffix }}
          tag: ${{ github.ref }}
