name: Docker test builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        image: [gitops, repo-server]
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: false
          file: docker/${{ matrix.image }}/Dockerfile