name: Docker build

on:
  push:
    branches: [main, golang]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: false
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
