name: Golang tests

on:
  push:
    branches: [main, golang]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Golang tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19
      - name: run golang tests
        env:
          SOPS_AGE_KEY_FILE: ${{ github.workspace }}/test_assets/keys.txt
          GITOPS_ROOT_DIR: ${{ github.workspace }}
        run: go test ./...
