name: Golang tests

on:
  push:
    branches: [main, golang]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Golang tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: start soft-serve
        run: ./hack/soft-serve/start.sh
      - name: run golang tests
        env:
          SOPS_AGE_KEY_FILE: ${{ github.workspace }}/test_assets/keys.txt
          GITOPS_ROOT_DIR: ${{ github.workspace }}
        run: go test ./internal/... -race
