name: Golang tests

on:
  push:
    branches: [main, golang]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Golang tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: run golang tests
        run: |
          export SOPS_AGE_KEY_FILE=${PWD}/test_assets/keys.txt
          export GITOPS_ROOT_DIR=${PWD}
          go test ./...
