# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm publish

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Test & Publish
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: |
        npm install
        npm test
        npm version ${{ github.event.release.tag_name }}
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish

    - name: Push new version
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Package version upgrade