# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm publish

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup git user
      run: |
        git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

    - name: Setup node 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Test & Publish
      run: |
        npm install
        { npm version ${{ github.event.release.tag_name }} --no-git-tag-version & } || true
        npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        npm publish

    - name: Push new version
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Package version upgrade
