name: Release

on:
  push:
    tags:
      - 2.*

jobs:
  binaries:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        os: [ubuntu-latest, windows-latest, macos-11]
        include:
          - os: ubuntu-latest
            os_name: ubuntu
            artifact_suffix: ""
          - os: windows-latest
            os_name: windows
            artifact_suffix: ".exe"
          - os: macos-11
            os_name: macos
            artifact_suffix: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: golang build
        env:
          GOARCH: ${{ matrix.arch }}
        run: |
          cd cmd/gitops
          go build -ldflags="-s -w" .
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/cmd/gitops/gitops${{ matrix.artifact_suffix }}
          asset_name: gitops_${{ matrix.os_name }}_${{ matrix.arch }}${{ matrix.artifact_suffix }}
          tag: ${{ github.ref }}
  docker:
    strategy:
      fail-fast: false
      matrix:
        image: [gitops, repo-server]
    name: docker build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/mxcd/gitops/${{ matrix.image }}:${{ github.ref_name }}
          file: docker/${{ matrix.image }}/Dockerfile